remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Marble Maze"
description: "Tilt your way to the top! Pacs adventure continues!"
author:
  name: "Serio Valdez"

# Do not change the following line.
  copyright: true
